#!bin/python
# -*- coding: utf-8 -*-


# todo: there's gotta be an automatic way to do this
class PMModel(object):
    def __init__(self):
        self.state = '' # type: str

    def to_opened(self) -> None: ...

    def to_closed(self) -> None: ...

    def open(self) -> None: ...

    def close(self) -> None: ...

    def sync(self) -> None: ...

    def desync(self) -> None: ...

    def wait(self) -> None: ...

    def wakeup(self) -> None: ...

    def sleep(self) -> None: ...

    def activate(self) -> None: ...

    def passivate(self) -> None: ...


class PMSensor(object):
    pass